// Copyright (C) 2026 HyPrism Launcher
// SPDX-License-Identifier: GPL-3.0-only

namespace HyPrism.Services.User;

/// <summary>
/// Presents an OAuth authorization URI through the active application host
/// </summary>
/// <param name="authorizationUri">The absolute authorization URI generated by Core</param>
/// <param name="cancellationToken">Token checked before the host presents the URI</param>
/// <returns><see langword="true"/> when the host accepts the presentation request; otherwise, <see langword="false"/></returns>
public delegate Task<bool> AuthUriPresenter(
    Uri authorizationUri,
    CancellationToken cancellationToken);
