# Copyright (C) 2026 HyPrism Launcher
# SPDX-License-Identifier: GPL-3.0-only

version = 1
SPDX-PackageName = "HyPrism"
SPDX-PackageSupplier = "HyPrism contributors"
SPDX-PackageDownloadLocation = "https://github.com/hyprismteam/HyPrism"

[[annotations]]
path = [
    "*.json",
    "**/*.json",
    "**/*.md5",
    "**/.hintrc",
    "**/*.png",
    "**/*.jpg",
    "**/*.ogg",
    "**/*.ico",
    "**/*.icns",
    "HyPrism.sln"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 HyPrism Launcher"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "Sources/HyPrism.Desktop/Assets/Fonts/GoogleSans-*.ttf"
precedence = "aggregate"
SPDX-FileCopyrightText = "Google LLC"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "Sources/HyPrism.Desktop/Assets/Fonts/JetBrainsMono-*.ttf"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 The JetBrains Mono Project Authors (https://github.com/JetBrains/JetBrainsMono)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "Sources/HyPrism.Desktop/Assets/Fluent/*.png"
precedence = "override"
SPDX-FileCopyrightText = "Icons8 LLC"
SPDX-License-Identifier = "LicenseRef-Icons8"
