<Project Sdk="Microsoft.NET.Sdk">

  <!--
  Copyright (C) 2026 HyPrism Launcher
  SPDX-License-Identifier: GPL-3.0-only
  -->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>HyPrism.Mesh</AssemblyName>
    <RootNamespace>HyPrism.Mesh</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
  </ItemGroup>

</Project>
