// Copyright (C) 2026 HyPrism Launcher
// SPDX-License-Identifier: GPL-3.0-only

// Generated by Scripts/generate_mdx_registry.py
// Edit the localized MDX trees instead of this file

import type { Locale } from '../_dictionaries/types'
import * as EnPage0 from '../../content/en/index.mdx'
import * as EnPage1 from '../../content/en/architecture/core.mdx'
import * as EnPage2 from '../../content/en/architecture/data-and-cache.mdx'
import * as EnPage3 from '../../content/en/architecture/desktop.mdx'
import * as EnPage4 from '../../content/en/architecture/overview.mdx'
import * as EnPage5 from '../../content/en/development/building.mdx'
import * as EnPage6 from '../../content/en/development/coding-style.mdx'
import * as EnPage7 from '../../content/en/development/contributing.mdx'
import * as EnPage8 from '../../content/en/development/documentation.mdx'
import * as EnPage9 from '../../content/en/development/localization.mdx'
import * as EnPage10 from '../../content/en/development/testing.mdx'
import * as EnPage11 from '../../content/en/getting-started/first-run.mdx'
import * as EnPage12 from '../../content/en/getting-started/installation.mdx'
import * as EnPage13 from '../../content/en/migration.mdx'
import * as EnPage14 from '../../content/en/reference/configuration.mdx'
import * as EnPage15 from '../../content/en/reference/mirrors.mdx'
import * as EnPage16 from '../../content/en/reference/services.mdx'
import * as EnPage17 from '../../content/en/user-guide/dashboard.mdx'
import * as EnPage18 from '../../content/en/user-guide/instances-profiles-mods.mdx'
import * as EnPage19 from '../../content/en/user-guide/news.mdx'
import * as EnPage20 from '../../content/en/user-guide/settings.mdx'
import * as RuPage0 from '../../content/ru/index.mdx'
import * as RuPage1 from '../../content/ru/architecture/core.mdx'
import * as RuPage2 from '../../content/ru/architecture/data-and-cache.mdx'
import * as RuPage3 from '../../content/ru/architecture/desktop.mdx'
import * as RuPage4 from '../../content/ru/architecture/overview.mdx'
import * as RuPage5 from '../../content/ru/development/building.mdx'
import * as RuPage6 from '../../content/ru/development/coding-style.mdx'
import * as RuPage7 from '../../content/ru/development/contributing.mdx'
import * as RuPage8 from '../../content/ru/development/documentation.mdx'
import * as RuPage9 from '../../content/ru/development/localization.mdx'
import * as RuPage10 from '../../content/ru/development/testing.mdx'
import * as RuPage11 from '../../content/ru/getting-started/first-run.mdx'
import * as RuPage12 from '../../content/ru/getting-started/installation.mdx'
import * as RuPage13 from '../../content/ru/migration.mdx'
import * as RuPage14 from '../../content/ru/reference/configuration.mdx'
import * as RuPage15 from '../../content/ru/reference/mirrors.mdx'
import * as RuPage16 from '../../content/ru/reference/services.mdx'
import * as RuPage17 from '../../content/ru/user-guide/dashboard.mdx'
import * as RuPage18 from '../../content/ru/user-guide/instances-profiles-mods.mdx'
import * as RuPage19 from '../../content/ru/user-guide/news.mdx'
import * as RuPage20 from '../../content/ru/user-guide/settings.mdx'

const englishPages = {
  '': EnPage0,
  'architecture/core': EnPage1,
  'architecture/data-and-cache': EnPage2,
  'architecture/desktop': EnPage3,
  'architecture/overview': EnPage4,
  'development/building': EnPage5,
  'development/coding-style': EnPage6,
  'development/contributing': EnPage7,
  'development/documentation': EnPage8,
  'development/localization': EnPage9,
  'development/testing': EnPage10,
  'getting-started/first-run': EnPage11,
  'getting-started/installation': EnPage12,
  'migration': EnPage13,
  'reference/configuration': EnPage14,
  'reference/mirrors': EnPage15,
  'reference/services': EnPage16,
  'user-guide/dashboard': EnPage17,
  'user-guide/instances-profiles-mods': EnPage18,
  'user-guide/news': EnPage19,
  'user-guide/settings': EnPage20,
}

export type MdxPageKey = keyof typeof englishPages

export const localizedPages = {
  en: englishPages,
  ru: {
    '': RuPage0,
    'architecture/core': RuPage1,
    'architecture/data-and-cache': RuPage2,
    'architecture/desktop': RuPage3,
    'architecture/overview': RuPage4,
    'development/building': RuPage5,
    'development/coding-style': RuPage6,
    'development/contributing': RuPage7,
    'development/documentation': RuPage8,
    'development/localization': RuPage9,
    'development/testing': RuPage10,
    'getting-started/first-run': RuPage11,
    'getting-started/installation': RuPage12,
    'migration': RuPage13,
    'reference/configuration': RuPage14,
    'reference/mirrors': RuPage15,
    'reference/services': RuPage16,
    'user-guide/dashboard': RuPage17,
    'user-guide/instances-profiles-mods': RuPage18,
    'user-guide/news': RuPage19,
    'user-guide/settings': RuPage20,
  }
} satisfies Record<Locale, Record<MdxPageKey, typeof EnPage0>>
