<!--
Copyright (C) 2026 Hyprism Launcher
SPDX-License-Identifier: GPL-3.0-only
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Hyprism.Desktop</AssemblyName>
    <ApplicationTitle>Hyprism Launcher</ApplicationTitle>
    <Product>Hyprism Launcher</Product>
    <TargetFramework>net10.0</TargetFramework>
    <Version>4.0.0</Version>
    <ApplicationIcon>Assets/Images/Hyprism.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.8.2" />
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Labs.Lottie" Version="12.0.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="DiscordRichPresence" Version="1.143.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Hyprism.Core/Hyprism.Core.csproj" />
    <ProjectReference Include="../Hyprism.LocalNode/Hyprism.LocalNode.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>

</Project>
