#!/usr/bin/env python3

# Copyright (C) 2026 HyPrism Launcher
# SPDX-License-Identifier: GPL-3.0-only

"""Generate the client-side registry for localized documentation pages"""

from __future__ import annotations

from pathlib import Path
import os
import sys


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "Docs"
CONTENT = DOCS / "content"
REGISTRY = DOCS / "app" / "_components" / "mdx-registry.generated.ts"
LOCALES = ("en", "ru")


def route_for(path: Path, locale: str) -> str:
    relative = path.relative_to(CONTENT / locale).with_suffix("")
    parts = list(relative.parts)
    if parts[-1] == "index":
        parts.pop()
    return "/".join(parts)


def collect_pages(locale: str) -> dict[str, Path]:
    pages: dict[str, Path] = {}
    for path in sorted((CONTENT / locale).rglob("*.mdx")):
        route = route_for(path, locale)
        if route in pages:
            first = pages[route].relative_to(ROOT)
            second = path.relative_to(ROOT)
            raise ValueError(f"Route {route!r} is declared by both {first} and {second}")
        pages[route] = path
    return pages


def check_parity(pages: dict[str, dict[str, Path]]) -> None:
    english_routes = set(pages["en"])
    russian_routes = set(pages["ru"])
    errors = [
        *(f"Russian page is missing for route {route!r}" for route in sorted(english_routes - russian_routes)),
        *(f"English page is missing for route {route!r}" for route in sorted(russian_routes - english_routes)),
    ]
    if errors:
        raise ValueError("\n".join(errors))
    if not english_routes:
        raise ValueError("No MDX pages were found")


def quote(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def import_path(path: Path) -> str:
    relative = os.path.relpath(path, REGISTRY.parent).replace(os.sep, "/")
    return relative if relative.startswith(".") else f"./{relative}"


def render_registry(pages: dict[str, dict[str, Path]]) -> str:
    routes = sorted(pages["en"])
    lines = [
        "// Copyright (C) 2026 HyPrism Launcher",
        "// SPDX-License-Identifier: GPL-3.0-only",
        "",
        "// Generated by Scripts/generate_mdx_registry.py",
        "// Edit the localized MDX trees instead of this file",
        "",
        "import type { Locale } from '../_dictionaries/types'",
    ]

    aliases: dict[str, dict[str, str]] = {locale: {} for locale in LOCALES}
    for locale in LOCALES:
        prefix = locale.capitalize()
        for index, route in enumerate(routes):
            alias = f"{prefix}Page{index}"
            aliases[locale][route] = alias
            lines.append(
                f"import * as {alias} from {quote(import_path(pages[locale][route]))}"
            )

    lines.extend(["", "const englishPages = {"])
    for route in routes:
        lines.append(f"  {quote(route)}: {aliases['en'][route]},")
    lines.extend(["}", "", "export type MdxPageKey = keyof typeof englishPages", ""])
    lines.extend(["export const localizedPages = {", "  en: englishPages,", "  ru: {"])
    for route in routes:
        lines.append(f"    {quote(route)}: {aliases['ru'][route]},")
    lines.extend(
        [
            "  }",
            f"}} satisfies Record<Locale, Record<MdxPageKey, typeof {aliases['en'][routes[0]]}>>",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    try:
        pages = {locale: collect_pages(locale) for locale in LOCALES}
        check_parity(pages)
        generated = render_registry(pages)
    except ValueError as error:
        print(f"MDX registry generation failed\n{error}", file=sys.stderr)
        return 1

    current = REGISTRY.read_text(encoding="utf-8") if REGISTRY.exists() else None
    if current == generated:
        print("MDX registry is up to date")
        return 0

    REGISTRY.write_text(generated, encoding="utf-8")
    print(f"Generated {REGISTRY.relative_to(ROOT)} with {len(pages['en'])} routes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
