<!--
Copyright (C) 2026 HyPrism Launcher
SPDX-License-Identifier: GPL-3.0-only
-->

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HyPrism.LocalNode</AssemblyName>
    <RootNamespace>HyPrism.LocalNode</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../HyPrism.Core/HyPrism.Core.csproj" />
  </ItemGroup>

</Project>
