# Copyright (C) 2026 HyPrism Launcher
# SPDX-License-Identifier: GPL-3.0-only

name: Build Nix package

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Nix x86_64-linux
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ github.token }}

      - name: Check and build flake
        run: nix flake check --print-build-logs
        working-directory: Packaging/linux/flake
